FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
WORKDIR /app
EXPOSE 80
COPY Shared/SISECommerce.Shared/*.csproj Shared/SISECommerce.Shared/
COPY Services/Discount/SISEcommerce.Services.Discount/*.csproj Services/Discount/SISEcommerce.Services.Discount/
RUN dotnet restore Services/Discount/SISEcommerce.Services.Discount/*.csproj
COPY . .
RUN dotnet publish Services/Discount/SISEcommerce.Services.Discount/*.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT [ "dotnet", "SISEcommerce.Services.Discount.dll" ]

